import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";

const windowWidth = Dimensions.get("window").width;

const styles = StyleSheet.create({
  btncerrarStyles: {
    borderRadius: 20,
    backgroundColor: "red",
    marginBottom: 10,
    marginTop: 10,
  },
  btnActualizarStyles: {
    borderRadius: 20,
    backgroundColor: "#2A3B76",
  },
  btnTextStyle: {
    color: "#ffff",
    fontWeight: "bold",
  },
  AndroidSafeArea: {
    flex: 1,
    backgroundColor: "#F4F6FA",
    paddingTop: Platform.OS === "android" ? (StatusBar as any).currentHeight : 0,
  },
  pageWrap: {
    maxWidth: 900,
    alignSelf: "center",
    width: "100%",
    paddingBottom: 32,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginVertical: 12,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#2A3B76",
    marginBottom: 14,
  },
  sectionSubtitle: {
    fontSize: 13,
    color: "#5A6478",
    marginBottom: 16,
    lineHeight: 20,
  },
  dashHeader: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 4,
  },
  dashHeaderTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1A1F36",
  },
  dashHeaderMeta: {
    fontSize: 13,
    color: "#5A6478",
    marginTop: 4,
  },
  statsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 8,
    gap: 10,
  },
  statCard: {
    width: Platform.OS === "web" ? "48%" : windowWidth / 2 - 22,
    backgroundColor: "white",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E8ECF4",
    flexDirection: "row",
    alignItems: "center",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 2px 10px rgba(42,59,118,0.06)" as any }
      : {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 4,
          elevation: 2,
        }),
  },
  statIconContainer: {
    width: 46,
    height: 46,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  statTextContainer: {
    flex: 1,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "700",
    color: "#2A3B76",
  },
  statLabel: {
    fontSize: 12,
    color: "#5A6478",
    marginTop: 2,
  },
  statHint: {
    fontSize: 10,
    color: "#9AA5B8",
    marginTop: 2,
  },
  card: {
    backgroundColor: "white",
    marginHorizontal: 15,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8ECF4",
    ...(Platform.OS === "web"
      ? { boxShadow: "0 2px 12px rgba(42,59,118,0.06)" as any }
      : {
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.06,
          shadowRadius: 6,
          elevation: 2,
        }),
  },
  activitySummary: {
    backgroundColor: "white",
    marginHorizontal: 15,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8ECF4",
  },
  barChartContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 160,
    paddingTop: 28,
  },
  barChartColumn: {
    alignItems: "center",
    flex: 1,
  },
  barLabelContainer: {
    position: "absolute",
    top: -22,
    alignItems: "center",
  },
  barValue: {
    fontSize: 11,
    fontWeight: "600",
    color: "#2A3B76",
  },
  bar: {
    width: 14,
    borderRadius: 7,
    marginBottom: 8,
    minHeight: 4,
  },
  barLabel: {
    fontSize: 11,
    color: "#5A6478",
  },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F2F7",
  },
  leaderboardRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#EEF1FA",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  leaderboardRankText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2A3B76",
  },
  leaderboardRankTop: {
    backgroundColor: "#2A3B76",
  },
  leaderboardRankTextTop: {
    color: "#fff",
  },
  leaderboardInfo: {
    flex: 1,
  },
  leaderboardName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1F36",
  },
  leaderboardEmail: {
    fontSize: 11,
    color: "#9AA5B8",
    marginTop: 1,
  },
  leaderboardCount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2A3B76",
  },
  leaderboardCountLabel: {
    fontSize: 10,
    color: "#9AA5B8",
    textAlign: "right",
  },
  recentActivityContainer: {
    backgroundColor: "white",
    marginHorizontal: 15,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E8ECF4",
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F2F7",
  },
  activityIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  activityDetails: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1A1F36",
  },
  activityDate: {
    fontSize: 11,
    color: "#9AA5B8",
    marginTop: 2,
  },
  activityEtapa: {
    fontSize: 11,
    color: "#2A3B76",
    fontWeight: "600",
    backgroundColor: "#EEF1FA",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    overflow: "hidden",
  },
  emptyText: {
    fontSize: 13,
    color: "#9AA5B8",
    textAlign: "center",
    paddingVertical: 20,
  },
  loadingWrap: {
    paddingVertical: 40,
    alignItems: "center",
  },
  aiCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#D9E6FF",
    backgroundColor: "#F8FAFF",
  },
  aiCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    paddingBottom: 10,
    gap: 12,
  },
  aiIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#2A3B76",
    alignItems: "center",
    justifyContent: "center",
  },
  aiTitleWrap: {
    flex: 1,
  },
  aiTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1F36",
  },
  aiBadge: {
    alignSelf: "flex-start",
    marginTop: 4,
    backgroundColor: "#FFF4EC",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  aiBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#C45C26",
    letterSpacing: 0.5,
  },
  aiDescription: {
    fontSize: 13,
    color: "#5A6478",
    lineHeight: 20,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  aiChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  aiChip: {
    backgroundColor: "#EEF1FA",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D7DDE9",
  },
  aiChipText: {
    fontSize: 12,
    color: "#5A6478",
  },
  aiInputRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 16,
    gap: 10,
  },
  aiInput: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D7DDE9",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "web" ? 12 : 10,
    fontSize: 14,
    color: "#1A1F36",
  } as any,
  aiSendBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#9AA5B8",
    alignItems: "center",
    justifyContent: "center",
  },
  aiDisabledNote: {
    fontSize: 11,
    color: "#9AA5B8",
    textAlign: "center",
    paddingBottom: 14,
    paddingHorizontal: 16,
  },
});

export default styles;
